# Generated by Django 4.1.6 on 2023-02-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdata',
            name='profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='sale_date',
            field=models.DateField(null=True),
        ),
    ]
